$terminal = alacritty
$menu = fuzzel
$browser = firefox

$mainMod = SUPER # Sets "Windows" key as main modifier

# Exec
bind = $mainMod, Y, exec, $terminal
bind = $mainMod, O, exec, $menu
bind = $mainMod, U, exec, $browser
bind = $mainMod, P, exec, ~/.config/hypr/wallpaper.sh


# Ending
bind = $mainMod, Return, killactive,
bind = $mainMod, Backspace, exit,

# dwindle
bind = $mainMod SHIFT, P, pseudo, 
bind = $mainMod SHIFT, J, togglesplit,

bind = $mainMod, Space, togglefloating,
bind = $mainMod, F, fullscreen,

# Move focus with
bind = $mainMod, L, movefocus, l
bind = $mainMod, H, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Resize
bind = $mainMod, left, resizeactive, -20 0
bind = $mainMod, right, resizeactive, 20 0
bind = $mainMod, up, resizeactive, 0 -20
bind = $mainMod, down, resizeactive, 0 20

# Workspaces
bind = $mainMod, 7, workspace, 1
bind = $mainMod, 8, workspace, 2
bind = $mainMod, 9, workspace, 3
bind = $mainMod, 0, workspace, 4

# ',' and '.' move window to the next and previus workspace, respectively
bind = $mainMod, code:59, movetoworkspace, e+1
bind = $mainMod, code:60, movetoworkspace, e-1
# '´', '[', '~', ']'
bind = $mainMod, code:34, movetoworkspace, 1
bind = $mainMod, code:35, movetoworkspace, 2
bind = $mainMod, code:48, movetoworkspace, 3
bind = $mainMod, code:51, movetoworkspace, 4

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -n s 10%-


